data:
  image_size: 128
  voxel_size: 32
  batch_size: 4
  num_workers: 2
  class_id: "03001627"

model:
  latent_dim: 1024

training:
  epochs: 20
  lr: 0.0001
  device: "cuda"

paths:
  rendering_dir: "C:/Shivansh/aiml/shapenet/src/data/ShapeNetRendering/ShapeNetRendering"
  voxel_dir: "C:/Shivansh/aiml/shapenet/src/data/ShapeNetVox32"
  output_dir: "./outputs"